#!/bin/bash

FILENAME='.lols';

case "$1" in
    g)
        read -s PASSWORD;
        read KEY;
        openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD | grep $KEY;
        ;;
    p)
        read -s PASSWORD;
        read KEY;
        read -s VALUE;
        if [ ! -f ~/$FILENAME ]; then
            echo -e "$KEY\t$VALUE" | openssl aes-128-cbc -a -out ~/$FILENAME -k $PASSWORD;
        else
            PREVIOUS=`openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD`;
            echo -e "$PREVIOUS\n$KEY\t$VALUE" | openssl aes-128-cbc -a -out ~/$FILENAME -k $PASSWORD;
        fi
        ;;
    d)
        read -s PASSWORD;
        read KEY;
        PREVIOUS=`openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD | grep -v $KEY`;
        echo $PREVIOUS | openssl aes-128-cbc -a -out ~/$FILENAME -k $PASSWORD;
        ;;
    a)
        read -s PASSWORD;
        openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD;
        ;;
    b)
        if [ "$2" != "" ]; then
            scp ~/$FILENAME $2:~/$FILENAME;
        else
            echo You must provide hostname;
        fi
        ;;
    s)
        if [ "$2" != "" ]; then
            if [ -f ~/$FILENAME ]; then
                echo ~/$FILENAME exists, whoops.
            else
                scp $2:~/$FILENAME ~/$FILENAME;
            fi
        else
            echo You must provide hostname;
        fi
        ;;
    m)
        read MAIL
        gpg -r $MAIL -a -e ~/$FILENAME && cat ~/${FILENAME}.asc | mail -s "~/$FILENAME" "$MAIL";
        rm -f ~/${FILENAME}.asc;
        ;;
esac
