#!/bin/bash

FILENAME='.lols';

case "$1" in
    g)
        read -s PASSWORD;
        read KEY;
        openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD | grep $KEY;
        ;;
    p)
        read -s PASSWORD;
        read KEY;
        read -s VALUE;
        if [ ! -f ~/$FILENAME ]; then
            echo -e "$KEY\t$VALUE" | openssl aes-128-cbc -a -out ~/$FILENAME -k $PASSWORD;
        else
            PREVIOUS=`openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD`;
            echo -e "$PREVIOUS\n$KEY\t$VALUE" | openssl aes-128-cbc -a -out ~/$FILENAME -k $PASSWORD;
        fi
        ;;
    d)
        read -s PASSWORD;
        read KEY;
        PREVIOUS=`openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD | grep -v $KEY`;
        echo $PREVIOUS | openssl aes-128-cbc -a -out ~/$FILENAME -k $PASSWORD;
        ;;
    a)
        read -s PASSWORD;
        openssl aes-128-cbc -a -d -in ~/$FILENAME -k $PASSWORD;
        ;;
esac
